services:
  back-end:
    build: ./back-end
    image: softy-pinko-back-end:task5
    ports:
      - "5252:5252"
  front-end:
    build: ./front-end
    image: softy-pinko-front-end:task5
    ports:
      - "9000:9000"
  proxy:
    build: ./proxy
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end